### ISSUE TITLE
Internal server error when User Path and Token headers exist

### ISSUE THREAD

**Issue by cbotsikas** [policycompass/policycompass#302]
If the user is logged in and user path and token headers exists, then there are some "HTTP Error 400: Bad Request" responses. Check mailing list thread "[pcompass-wp3] stage server" from 21/10/2015 for more details

![bug](https://cloud.githubusercontent.com/assets/1640100/10632169/e1674238-77e2-11e5-8ed7-156f764a21cd.jpg)

**Comment by cbotsikas** [comment]
@nidico can you address this issue?

**Comment by cbotsikas** [comment]
HTTPError at /api/v1/references/languages/38
HTTP Error 400: Bad Request
Request Method:	GET
Request URL:	http://services-stage.policycompass.eu/api/v1/references/languages/38
Django Version:	1.7
Exception Type:	HTTPError
Exception Value:	
HTTP Error 400: Bad Request
Exception Location:	/usr/lib/python3.4/urllib/request.py in http_error_default, line 587
Python Executable:	/home/policycompass/policycompass/policycompass-services/bin/python
Python Version:	3.4.0
Python Path:	
['/home/policycompass/policycompass/policycompass-services',
 '/home/policycompass/policycompass/policycompass-services/lib/python3.4',
 '/home/policycompass/policycompass/policycompass-services/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/policycompass/policycompass/policycompass-services/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages']
Server time:	Wed, 21 Oct 2015 08:14:17 +0000

**Comment by cbotsikas** [comment]
And the traceback:

File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/rest_framework/viewsets.py" in view
  78.             return self.dispatch(request, *args, **kwargs)
File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/django/views/decorators/csrf.py" in wrapped_view
  57.         return view_func(*args, **kwargs)
File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/rest_framework/views.py" in dispatch
  401.             response = self.handle_exception(exc)
File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/rest_framework/views.py" in dispatch
  389.             self.initial(request, *args, **kwargs)
File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/rest_framework/views.py" in initial
  318.         self.perform_authentication(request)
File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/rest_framework/views.py" in perform_authentication
  268.         request.user
File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/rest_framework/request.py" in user
  226.             self._authenticate()
File "/home/policycompass/policycompass/policycompass-services/lib/python3.4/site-packages/rest_framework/request.py" in _authenticate
  401.                 user_auth_tuple = authenticator.authenticate(self)
File "/home/policycompass/policycompass/policycompass-services/policycompass_services/auth.py" in authenticate
  103.         response = urlopen(request)
File "/usr/lib/python3.4/urllib/request.py" in urlopen
  161.     return opener.open(url, data, timeout)
File "/usr/lib/python3.4/urllib/request.py" in open
  469.             response = meth(req, response)
File "/usr/lib/python3.4/urllib/request.py" in http_response
  579.                 'http', request, response, code, msg, hdrs)
File "/usr/lib/python3.4/urllib/request.py" in error
  507.             return self._call_chain(*args)
File "/usr/lib/python3.4/urllib/request.py" in _call_chain
  441.             result = func(*args)
File "/usr/lib/python3.4/urllib/request.py" in http_error_default
  587.         raise HTTPError(req.full_url, code, msg, hdrs, fp)

Exception Type: HTTPError at /api/v1/references/languages/38
Exception Value: HTTP Error 400: Bad Request

**Comment by nidico** [comment]
Unfortunately, I can only reproduce it on staging, but not locally. This needs further debugging.

**Comment by mmilaprat** [comment]
I can reproduce this error in my local environment, I have the same problem.  My config.js is:

var policyCompassConfig = {
    'URL': '/api/v1',
    'DATASETS_MANAGER_URL': 'http://localhost:8000/api/v1/datasetmanager',
    'VISUALIZATIONS_MANAGER_URL': 'http://localhost:8000/api/v1/visualizationsmanager',
    'EVENTS_MANAGER_URL': 'http://localhost:8000/api/v1/eventsmanager',
    'METRICS_MANAGER_URL': 'http://localhost:8000/api/v1/metricsmanager',
    'SEARCH_MANAGER_URL': 'http://localhost:8000/api/v1/searchmanager',
    'FORMULA_VALIDATION_URL' : 'http://localhost:8000/api/v1/metricsmanager/formulas/validate',
    'NORMALIZERS_URL': 'http://localhost:8000/api/v1/metricsmanager/normalizers',
    'REFERENCE_POOL_URL': 'http://localhost:8000/api/v1/references',
    'INDICATOR_SERVICE_URL': 'http://localhost:8000/api/v1/indicatorservice',
    'FCM_URL': 'http://localhost:8080/api/v1/fcmmanager',
    'ELASTIC_URL' : 'http://localhost:9200/',
    'server_ELASTIC_URL' : 'https://search-stage.policycompass.eu/',
    'ELASTIC_INDEX_NAME' : 'policycompass_search',
    'ENABLE_ADHOCRACY': true,
    'ADHOCRACY_BACKEND_URL': 'https://adhocracy-frontend-stage.policycompass.eu/api',
    'ADHOCRACY_FRONTEND_URL': 'https://adhocracy-frontend-stage.policycompass.eu'
};

I started django server:
python manage.py runserver 0.0.0.0:8000

**Comment by nidico** [comment]
The installer indicated that some migrations were missing, so I did `makemigrations` & `migrate` on the django services on staging, and now I can't reproduce this issue anymore.

@mmilaprat, @cbotsikas - can anybody of you still reproduce this? If not, please close this issue.

**Comment by mmilaprat** [comment]
I clear my cache and the error persist in the stage server.

![21-10-2015 13-52-54](https://cloud.githubusercontent.com/assets/6602727/10635733/38dd5c06-77fb-11e5-9549-8627b2196343.png)

**Comment by FabiApfelkern** [comment]
The error comes from this line: https://github.com/policycompass/policycompass-services/blob/master/policycompass_services/auth.py#L103
The requests fails for some reason.

**Comment by nidico** [comment]
Maybe adhocracy is blocking for a reason, similar to #301. You may want to merge #310 and see if this issue still persists.

**Comment by FabiApfelkern** [comment]
I merged it but it's no difference. But I'm not sure if I locally use those ini files. Where is this configured?

**Comment by nidico** [comment]
If you use the makefile to build adhocracy, run `make adhocracy3_install` and `supervisorctl restart adhocracy:`. The former should make `adhocracy3/etc/development.ini` a link to `etc/.../development.ini`.

**Comment by FabiApfelkern** [comment]
Ok, it was already like this. So it doesn't help.

**Comment by nidico** [comment]
I can look into this a bit later today.

**Comment by FabiApfelkern** [comment]
Thank you!

**Comment by FabiApfelkern** [comment]
@nidico I deployed the latest version after merging. Now it is working on alpha just fine, but not on stage. I don't know what the difference is. You changed something on the nginx.conf on Stage (I stashed that), but you haven't done it in Alpha. I would like to understand the mechanism causing that problem. I have also still on my local machine. Adhocracy is just accepting Requests from certain hosts?

**Comment by nidico** [comment]
> I don't know what the difference is.

Some naming fuckup. For some reason one is called `adhocracy-frontend-stage.policycompass.eu`, the other `adhocracy-prod.policycompass.eu`. I did a fixup in a2ff577ccb1.

> You changed something on the nginx.conf on Stage (I stashed that), but you haven't done it in Alpha.

@slomo changed `localhost` to `127.0.0.1` due to some broken IPv6 configuration on the staging server. Don't know if this is still relevant.

**Comment by nidico** [comment]
I deployed this on stage now, closing.

**Comment by mmilaprat** [comment]
just a question, it's possible to configure our local environments with a mix of our own PC backend (datasets, metrics, events, visualisations APIs) and the adhocracy backend?

I'm trying to use to check the authentication in the FE and  in the backend, but I still having the errors reported in this issue in the FE.

I use these end points:
'ADHOCRACY_BACKEND_URL': 'https://adhocracy-frontend-stage.policycompass.eu/api',
'ADHOCRACY_FRONTEND_URL': 'https://adhocracy-frontend-stage.policycompass.eu'

**Comment by nidico** [comment]
> just a question, it's possible to configure our local environments with a mix of our own PC backend (datasets, metrics, events, visualisations APIs) and the adhocracy backend?

Yes. The endpoints are fine, but you also need to configure the endpoint in the django services settings, i.e.

    'adhocracy_api_base_url': 'https://adhocracy-frontend-stage.policycompass.eu/api'

**Comment by mmilaprat** [comment]
it works, thanks!!
