### ISSUE TITLE
Theme Adhocracy similar to PolicyCompass

### ISSUE THREAD

**Issue by nidico** [policycompass/policycompass#89]
Adjust colors, basic fonts etc in order to make it look like a part of PolicyCompass.

**Comment by FabiApfelkern** [comment]
@nidico Nobody is assigned to this one!?

**Comment by nidico** [comment]
Fixed through #187.

**Comment by YuriGlickman** [comment]
I think it has been discussed. The width of the adhocracy window has to be the same as the width of the Policy Compass page and not 1/3 of its width.

**Comment by nidico** [comment]
We'll check what is possible.

**Comment by FabiApfelkern** [comment]
I'm still not happy with this. Now you just moved it to the left side, but it is still small. 

![screenshot from 2015-09-09 10-28-25](https://cloud.githubusercontent.com/assets/1488424/9756894/8c2353dc-56dd-11e5-88af-db1abb65a0de.png)

**Comment by nidico** [comment]
This has been done like that on purpose. Using the full width is not an option as it would allow way to many words in one line, both in the input field as well in the actual comments.

The discussion has not only been moved to the side, but it has been aligned with a layout which actually exists in policycompass, i.e. full width of the `col-lg-6` grid. This means it isn't too broad on big screens, but degrades to the full width automatically on smaller screens.

@FabiApfelkern - we talked about that at length yesterday, including our designers. This is the best we could come up without changing the site layout entirely. If you have any alternative propsals, which take into account maximum line lengths, please state them. Otherwise please close the issue.

**Comment by FabiApfelkern** [comment]
I don't have good suggestion. But for sure it is possible. :) Actually this discussion in GitHub is much wider and I have no problem to read it. But if you say it is impossible, we will find a way to incorporate it into the design. We can do it in this ticket: https://github.com/policycompass/policycompass/issues/200
